/* Reads a Figma token export and injects the values into the prototype.
   Supports both the W3C DTCG shape ($value/$type) and the Tokens Studio
   shape (value/type). Aliases like {color.brand.red} are resolved.

   Usage: node scripts/build-tokens.mjs [tokens/zanaco.tokens.json]  */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const TOKENS = process.argv[2] || "tokens/zanaco.tokens.json";
const MAPPING = "tokens/mapping.json";
const TARGET = "prototype/index.html";

if (!existsSync(TOKENS)) {
  console.error(`No token file at ${TOKENS}. Export from Figma first — see tokens/README.md.`);
  process.exit(1);
}

const flat = new Map();
(function walk(node, path) {
  if (node === null || typeof node !== "object") return;
  const value = node.$value !== undefined ? node.$value : node.value;
  if (value !== undefined && typeof value !== "object") {
    flat.set(path.join("."), String(value));
    return;
  }
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$") || k === "type" || k === "description") continue;
    walk(v, [...path, k]);
  }
})(JSON.parse(readFileSync(TOKENS, "utf8")), []);

const resolve = (raw, seen = new Set()) => {
  const m = /^\{([^}]+)\}$/.exec(raw.trim());
  if (!m) return raw;
  const key = m[1];
  if (seen.has(key)) throw new Error(`Circular token alias: ${key}`);
  const next = flat.get(key);
  if (next === undefined) throw new Error(`Token alias {${key}} does not resolve`);
  return resolve(next, new Set([...seen, key]));
};

const mapping = JSON.parse(readFileSync(MAPPING, "utf8"));
const html = readFileSync(TARGET, "utf8");
const current = Object.fromEntries(
  [...html.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)].map(m => [m[1], m[2].trim()])
);

const lines = [];
const missing = [];
for (const [cssVar, tokenPath] of Object.entries(mapping)) {
  const raw = flat.get(tokenPath);
  if (raw === undefined) {
    missing.push(`${cssVar} ← ${tokenPath}`);
    if (current[cssVar]) lines.push(`  ${cssVar}:${current[cssVar]};`);
    continue;
  }
  lines.push(`  ${cssVar}:${resolve(raw)};`);
}

const block = [
  "  /* TOKENS:START — generated by scripts/build-tokens.mjs, do not edit by hand */",
  ...lines,
  "  /* TOKENS:END */",
].join("\n");

const out = html.replace(
  /[ \t]*\/\* TOKENS:START[\s\S]*?TOKENS:END \*\//,
  block
);
if (out === html) { console.error("Could not find the TOKENS markers in " + TARGET); process.exit(1); }
writeFileSync(TARGET, out);

console.log(`Wrote ${lines.length} token values into ${TARGET}`);
if (missing.length) {
  console.warn(`\nKept the existing value for ${missing.length} unmapped token(s):`);
  for (const m of missing) console.warn("  " + m);
  console.warn("\nEdit tokens/mapping.json so these point at real paths in your export.");
}
