/* Reads SVG icons exported from Figma and injects them into the prototype,
   replacing the drawn placeholder icons.

   Put the exported files in assets/icons/ and map them to the names the
   prototype uses in assets/icons/mapping.json:

     { "cart": "shopping-cart.svg", "home": "house-outline.svg", ... }

   A file whose basename already matches a needed name is picked up with no
   mapping entry. Run: node scripts/import-icons.mjs  */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, basename, extname } from "node:path";

const DIR = "assets/icons";
const TARGET = "prototype/index.html";
const NEEDED = ["cart","ticket","home","plane","grid","chev","search","back","arrow","shield",
  "coins","doc","car","bed","bus","leaf","heart","hammer","scale","spark","list","pin","film",
  "gym","store","wallet","book","calendar","users","broom","pill","tap","check"];

if (!existsSync(DIR)) { console.error(`No ${DIR}/ directory.`); process.exit(1); }

const files = readdirSync(DIR).filter(f => extname(f).toLowerCase() === ".svg");
if (!files.length) {
  console.error(`No SVG files in ${DIR}/. Export the icon set from Figma (node 3396-35698) as SVG and drop them in.`);
  process.exit(1);
}

const mapPath = join(DIR, "mapping.json");
const mapping = existsSync(mapPath) ? JSON.parse(readFileSync(mapPath, "utf8")) : {};
const byBase = new Map(files.map(f => [basename(f, ".svg").toLowerCase(), f]));

const parse = (svg) => {
  const vb = /viewBox\s*=\s*"([^"]+)"/i.exec(svg)?.[1] || "0 0 24 24";
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/gi, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<svg[^>]*>/i, "")
    .replace(/<\/svg>/i, "")
    .replace(/<title[\s\S]*?<\/title>/gi, "")
    .replace(/\s(width|height|class|id)\s*=\s*"[^"]*"/gi, "")
    .replace(/\s+/g, " ")
    .trim();
  // A stroked icon is recoloured via stroke; a filled one via fill.
  const stroked = /stroke\s*=\s*"(?!none)/i.test(body);
  const recoloured = stroked
    ? body.replace(/stroke\s*=\s*"(?!none)[^"]*"/gi, 'stroke="currentColor"')
    : body.replace(/fill\s*=\s*"(?!none)[^"]*"/gi, 'fill="currentColor"');
  return { vb, body: recoloured, stroked };
};

const out = {};
const unresolved = [];
for (const name of NEEDED) {
  const file = mapping[name] || byBase.get(name);
  if (!file || !existsSync(join(DIR, file))) { unresolved.push(name); continue; }
  out[name] = parse(readFileSync(join(DIR, file), "utf8"));
}

const block = [
  "/* ICONS:START — generated by scripts/import-icons.mjs from assets/icons/*.svg */",
  "const LIB=" + JSON.stringify(out) + ";",
  "/* ICONS:END */",
].join("\n");

const html = readFileSync(TARGET, "utf8");
const next = html.replace(/\/\* ICONS:START[\s\S]*?ICONS:END \*\//, block);
if (next === html) { console.error("Could not find the ICONS markers in " + TARGET); process.exit(1); }
writeFileSync(TARGET, next);

console.log(`Wired ${Object.keys(out).length} of ${NEEDED.length} icons from the library.`);
if (unresolved.length) {
  console.warn(`\nStill using drawn placeholders for: ${unresolved.join(", ")}`);
  console.warn(`Add them to ${mapPath}, e.g. { "${unresolved[0]}": "your-file.svg" }`);
}
